select 
DISTINCT(SLMN) [RepNumber],
REP,
CASE 
    WHEN REPSTACK.REP = 'GB CRITZER' THEN '03325' 
    WHEN REPSTACK.REP = 'JOHN MIKLICH' THEN '01834'
    ELSE EM_PSSR.MgrNum END [ManagerNum],
CASE 
    WHEN REPSTACK.REP = 'GB CRITZER' THEN 'BRADLEY SHEPPARD' 
    WHEN REPSTACK.REP = 'JOHN MIKLICH' THEN 'TIMOTHY MCCAULEY' 
    ELSE EM_PSSR.MgrName END [ManagerName],

CASE 
    WHEN EM_PSSR.MgrName = 'MICHAEL ESTEP' THEN 'Western RI'
    WHEN EM_PSSR.MgrName = 'MATTHEW COCOWITCH' THEN 'Western CI'
    WHEN EM_PSSR.MgrName = 'TIMOTHY MCCAULEY' AND REPSTACK.REP NOT IN ('SAM STALLARD','JOSH MARTIN') THEN 'MD-Delmv'
    WHEN EM_PSSR.MgrName = 'JOSHUA MARTIN' THEN 'Eastern'
    WHEN EM_PSSR.MgrName = 'BRADLEY SHEPPARD' OR REPSTACK.REP = 'GB CRITZER' THEN 'NOVA'
    WHEN EM_PSSR.MgrName = 'TIMOTHY MCCAULEY' AND REPSTACK.REP = 'SAM STALLARD' THEN 'SAM STALLARD'
    WHEN EM_PSSR.MgrName = 'STEVEN ANDERSON' THEN 'CSR/ISR'
	ELSE 'Other'
END AS Region,
CASE WHEN EM_PSSR.MgrName = 'MICHAEL ESTEP' THEN 'RI'
		 WHEN EM_PSSR.MgrName IN ('MATTHEW COCOWITCH', 'RICHARD MINTER','JOSHUA MARTIN','BRADLEY SHEPPARD','TODD TRUAX', 'STEVEN ANDERSON', 'TIMOTHY MCCAULEY') THEN 'CI'
	ELSE 'UNKN'
	END AS vertical
FROM GDM.dbo.RepAssignments REPSTACK
LEFT OUTER JOIN 
HR_DataStore.dbo.EmployeeMaster EM_PSSR WITH(NOLOCK) 
ON REPSTACK.REP = CASE 
                    WHEN EM_PSSR.Nickname IS NULL THEN CONCAT(EM_PSSR.FirstName,' ', EM_PSSR.LastName) 
                    WHEN CONCAT(EM_PSSR.Nickname, ' ', EM_PSSR.LastName) = 'JACK MIKLICH' THEN CONCAT(EM_PSSR.FirstName,' ', EM_PSSR.LastName)
                    ELSE CONCAT(EM_PSSR.Nickname, ' ', EM_PSSR.LastName) END
where REPSTACK.slmt = '3'
and divi = 'C'
and CASE WHEN REPSTACK.REP LIKE 'GB%' THEN '03325' ELSE EM_PSSR.MgrNum END in ('03490',	'08984', '03325',	'02374', '04414',	
'07610', '01834','08986','05108');