select 
DISTINCT(SLMN) [RepNumber],
REP,
CASE WHEN EM_PSSR.MgrNum IS NULL AND REPSTACK.REP = 'GB CRITZER' THEN '03325' ELSE MgrNum END [ManagerNum],
EM_PSSR.MgrName [ManagerName],
 CASE WHEN EM_PSSR.MgrName = 'WILLIAM HELTZEL' THEN 'Western RI'
		 WHEN EM_PSSR.MgrName = 'MATTHEW COCOWITCH' THEN 'Western CI'
		 WHEN EM_PSSR.MgrName = 'RICHARD MINTER' THEN 'MD-Delmv'
		 WHEN EM_PSSR.MgrName = 'JOSHUA MARTIN' THEN 'Eastern'
		 WHEN EM_PSSR.MgrName = 'BRADLEY SHEPPARD' THEN 'NOVA'
         WHEN EM_PSSR.MgrName = 'TODD TRUAX' THEN 'CSR'
         WHEN EM_PSSR.MgrName = 'TIMOTHY MCCAULEY' THEN 'SAM STALLARD'
         WHEN EM_PSSR.MgrName = 'STEVEN ANDERSON' THEN 'ISR'
	ELSE 'Other'
	END AS Region
FROM GDM.dbo.RepAssignments REPSTACK
LEFT OUTER JOIN 
HR_DataStore.dbo.EmployeeMaster EM_PSSR WITH(NOLOCK) 
ON REPSTACK.REP = CASE WHEN EM_PSSR.Nickname IS NULL THEN CONCAT(EM_PSSR.FirstName,' ', EM_PSSR.LastName) ELSE CONCAT(EM_PSSR.Nickname, ' ', EM_PSSR.LastName) END
where REPSTACK.slmt = '3'
and divi = 'C'
and MgrNum in ('03490',	'08984', '03325',	'02374',	'04414',	
'07610', '01834') 